spring:
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
