server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute #Identificando la ruta del service de producto
          uri: http://localhost:8082/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies
        - id: catalogRoute #Identificando la ruta del service de producto
          uri: http://localhost:8084/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/catalogs/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalogs
      
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
info:
  app:
    name: gateway-service
    description: Gateway Service
    version: 1.0.0
