server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute #Identificando la ruta del service de producto
          uri: lb://movie-service #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: movieService
                fallbackUri: forward:/fallback/movies
        - id: catalogRoute #Identificando la ruta del service de producto
          uri: lb://catalog-service #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/catalogs/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalogs
      

info:
  app:
    name: ${spring.application.name}
    description: Gateway Service
    version: 1.0.0
