server:
  port: 8080
  
spring:
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: movieRoute #Identificando la ruta del service de producto
          uri: lb://movie-service #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/movies/**
        - id: catalogRoute #Identificando la ruta del service de producto
          uri: lb://catalog-service #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/catalogs/**
        - id: serieRoute
          uri: lb://serie-service
          predicates:
            - Path=/series/**
            
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        
info:
  app:
    name: gateway-service
    description: Gateway Service
    version: 1.0.0
