server:
  port: 8082

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
  datasource:
    url: jdbc:mysql://mysqldb:3306/Movie
    username: root
    password: aledev123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:movie.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
queue:
  movie:
    name: Movie

info:
  app:
    name: movie-service
    description: Movie Service
    version: 1.0.0
